[[redirects]]
  from = "https://watchamoviewithcasey.com/*"
  to = "https://theheartbrokendev.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.watchamoviewithcasey.com/*"
  to = "https://theheartbrokendev.com/:splat"
  status = 301
  force = true
